hostname: orion
collectiondir: /work/noaa/stmp/mpotts/cpld_bmarkfrac_wave_v16
scheduler: "slurm"
artifactsdir: /work/noaa/stmp/mpotts/ufs-test-artifacts
scriptdir: /work/noaa/stmp/mpotts/ufs-test-artifacts/python_scripts
artifactname: cpld_bmarkfrac_wave_v16
collectedfiles:
  regex1: PET*
  regex2: out
  regex3: err
  regex4: ESMF_Profile*
  regex5: log*
  regex6: nems*
